services:
  postgres:
    image: postgres:15-alpine
    container_name: databridge-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: databridge
    ports:
      # Host:Contenedor
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d databridge"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
